param(
  [string]$InputCsv = (Join-Path $PSScriptRoot "..\outbound\data\prospects\prospects_initial_150.csv"),
  [string]$OutputSql = (Join-Path $PSScriptRoot "..\outbound\sql\generated\d1-outbound-seed-2026-04-21.sql"),
  [string]$CampaignId = "dashboard_comercial_test_v1",
  [string]$LocalDate = (Get-Date).ToString("yyyy-MM-dd"),
  [int]$BlockSize = 25
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Sql-String {
  param([object]$Value)
  if ($null -eq $Value) {
    return "NULL"
  }
  $text = [string]$Value
  if ($text.Length -eq 0) {
    return "NULL"
  }
  return "'" + ($text -replace "'", "''") + "'"
}

function To-UtcIso {
  param(
    [string]$Date,
    [string]$Time
  )

  $value = [DateTimeOffset]::Parse("$Date`T$Time`:00-03:00")
  return $value.UtcDateTime.ToString("yyyy-MM-ddTHH:mm:ss.000Z")
}

if (-not (Test-Path -LiteralPath $InputCsv)) {
  throw "Input CSV not found: $InputCsv"
}

$rows = @(Import-Csv -LiteralPath $InputCsv)
if ($rows.Count -eq 0) {
  throw "Input CSV is empty: $InputCsv"
}

$blocks = @("09:30", "10:45", "12:00", "13:30", "15:00", "16:30")
$scheduledAt = @()
foreach ($block in $blocks) {
  $utc = To-UtcIso -Date $LocalDate -Time $block
  for ($i = 0; $i -lt $BlockSize; $i++) {
    $scheduledAt += $utc
  }
}

if ($scheduledAt.Count -lt $rows.Count) {
  throw "Not enough schedule slots for $($rows.Count) rows."
}

$lines = New-Object "System.Collections.Generic.List[string]"
$lines.Add("-- Generated by scripts/build-outbound-seed.ps1") | Out-Null
$lines.Add("-- Campaign: $CampaignId") | Out-Null
$lines.Add("-- Local date: $LocalDate America/Buenos_Aires") | Out-Null
$lines.Add("") | Out-Null

$index = 0
foreach ($row in $rows) {
  $scheduled = $scheduledAt[$index]
  $queueId = "$CampaignId`:$($row.id):1"
  $index += 1

  $lines.Add(@"
INSERT OR REPLACE INTO outbound_prospects (
  id, company_name, website, domain, email, email_type, contact_route,
  contact_name, contact_role, industry, sub_industry, company_type,
  country, province, city, icp_fit, icp_score, priority, source,
  campaign_segment, sequence_id, sequence_step, status, tags,
  validation_flags, last_sent_at, next_send_at, replied_at, bounced_at,
  unsubscribed_at, do_not_contact_reason, notes, created_at, updated_at
) VALUES (
  $(Sql-String $row.id),
  $(Sql-String $row.company_name),
  $(Sql-String $row.website),
  $(Sql-String $row.domain),
  $(Sql-String $row.email),
  $(Sql-String $row.email_type),
  $(Sql-String $row.contact_route),
  $(Sql-String $row.contact_name),
  $(Sql-String $row.contact_role),
  $(Sql-String $row.industry),
  $(Sql-String $row.sub_industry),
  $(Sql-String $row.company_type),
  $(Sql-String $row.country),
  $(Sql-String $row.province),
  $(Sql-String $row.city),
  $(Sql-String $row.icp_fit),
  $([int]$row.icp_score),
  $(Sql-String $row.priority),
  $(Sql-String $row.source),
  $(Sql-String $row.campaign_segment),
  $(Sql-String $CampaignId),
  0,
  'scheduled',
  $(Sql-String $row.tags),
  $(Sql-String $row.validation_flags),
  NULL,
  $(Sql-String $scheduled),
  NULL,
  NULL,
  NULL,
  NULL,
  $(Sql-String $row.notes),
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
);

INSERT OR REPLACE INTO outbound_send_queue (
  id, campaign_id, prospect_id, step_number, scheduled_at, status,
  attempts, created_at, updated_at
) VALUES (
  $(Sql-String $queueId),
  $(Sql-String $CampaignId),
  $(Sql-String $row.id),
  1,
  $(Sql-String $scheduled),
  'pending',
  0,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
);
"@) | Out-Null
}

$lines.Add("") | Out-Null

$outputDirectory = Split-Path -Parent $OutputSql
New-Item -ItemType Directory -Path $outputDirectory -Force | Out-Null
$lines -join "`n" | Set-Content -LiteralPath $OutputSql -Encoding UTF8

[PSCustomObject]@{
  output_sql = $OutputSql
  campaign_id = $CampaignId
  local_date = $LocalDate
  rows = $rows.Count
  first_scheduled_utc = $scheduledAt[0]
  last_scheduled_utc = $scheduledAt[$rows.Count - 1]
}
