param(
  [string]$InputCsv = (Join-Path $PSScriptRoot "..\outbound\data\prospects\prospects_final.csv"),
  [string]$OutputCsv = (Join-Path $PSScriptRoot "..\outbound\data\prospects\prospects_ramp_5_business_days.csv"),
  [string]$OutputSql = (Join-Path $PSScriptRoot "..\outbound\sql\generated\d1-outbound-ramp-2026-04-21.sql"),
  [string]$CampaignId = "dashboard_comercial_test_v1",
  [string]$StartDate = "2026-04-21"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$Plan = @(
  @{ date = $StartDate; label = "day_1_validation"; status = "pending"; blocks = @("10:45", "13:30") },
  @{ date = "2026-04-22"; label = "day_2_if_metrics_ok"; status = "held"; blocks = @("09:30", "12:00", "15:00") },
  @{ date = "2026-04-23"; label = "day_3_if_metrics_ok"; status = "held"; blocks = @("09:30", "10:45", "13:30", "16:30") },
  @{ date = "2026-04-24"; label = "day_4_if_metrics_ok"; status = "held"; blocks = @("09:30", "12:00", "15:00") },
  @{ date = "2026-04-27"; label = "day_5_if_metrics_ok"; status = "held"; blocks = @("09:30") }
)

function Sql-String {
  param([object]$Value)
  if ($null -eq $Value) { return "NULL" }
  $text = [string]$Value
  if ($text.Length -eq 0) { return "NULL" }
  return "'" + ($text -replace "'", "''") + "'"
}

function Normalize-Key {
  param([object]$Value)
  if ($null -eq $Value) { return "" }
  return (([string]$Value).Trim().ToLowerInvariant() -replace "\s+", " ")
}

function To-UtcIso {
  param(
    [string]$Date,
    [string]$Time
  )
  $value = [DateTimeOffset]::Parse("$Date`T$Time`:00-03:00")
  return $value.UtcDateTime.ToString("yyyy-MM-ddTHH:mm:ss.000Z")
}

function Add-Slots {
  param(
    [System.Collections.Generic.List[object]]$Slots,
    [hashtable]$Day
  )

  foreach ($block in $Day.blocks) {
    for ($i = 0; $i -lt 25; $i++) {
      [void]$Slots.Add([PSCustomObject]@{
        local_date = $Day.date
        local_time = $block
        scheduled_at = To-UtcIso -Date $Day.date -Time $block
        queue_status = $Day.status
        ramp_label = $Day.label
      })
    }
  }
}

if (-not (Test-Path -LiteralPath $InputCsv)) {
  throw "Input CSV not found: $InputCsv"
}

$rows = @(Import-Csv -LiteralPath $InputCsv | Where-Object {
  $_.status -eq "approved" -and
  $_.priority -in @("A", "B") -and
  $_.email_type -ne "free_email" -and
  $_.campaign_segment -ne "revision_manual" -and
  $_.validation_flags -notmatch "needs_manual_review|possible_public_sector|possible_prior_sales_context"
})

$seen = @{}
$eligible = New-Object "System.Collections.Generic.List[object]"
foreach ($row in $rows) {
  $key = if ($row.domain) { Normalize-Key $row.domain } else { Normalize-Key $row.company_name }
  if (-not $key) { $key = Normalize-Key $row.email }
  if ($seen.ContainsKey($key)) { continue }
  $seen[$key] = $true
  [void]$eligible.Add($row)
}

$segmentOrder = @(
  "industrial_b2b_test",
  "agroindustrial_test",
  "distribuidores_prioridad_a_b"
)

$groups = @{}
foreach ($segment in $segmentOrder) {
  $groups[$segment] = New-Object "System.Collections.Queue"
}
foreach ($row in ($eligible | Sort-Object @{ Expression = { [int]$_.icp_score }; Descending = $true }, company_name)) {
  $segment = if ($segmentOrder -contains $row.campaign_segment) { $row.campaign_segment } else { "industrial_b2b_test" }
  $groups[$segment].Enqueue($row)
}

$ordered = New-Object "System.Collections.Generic.List[object]"
while (($groups.Values | ForEach-Object { $_.Count } | Measure-Object -Sum).Sum -gt 0) {
  foreach ($segment in $segmentOrder) {
    if ($groups[$segment].Count -gt 0) {
      [void]$ordered.Add($groups[$segment].Dequeue())
    }
  }
}

$slots = New-Object "System.Collections.Generic.List[object]"
foreach ($day in $Plan) {
  Add-Slots -Slots $slots -Day $day
}

$count = [Math]::Min($ordered.Count, $slots.Count)
$rampRows = New-Object "System.Collections.Generic.List[object]"
for ($i = 0; $i -lt $count; $i++) {
  $row = $ordered[$i]
  $slot = $slots[$i]
  $row | Add-Member -NotePropertyName ramp_local_date -NotePropertyValue $slot.local_date -Force
  $row | Add-Member -NotePropertyName ramp_local_time -NotePropertyValue $slot.local_time -Force
  $row | Add-Member -NotePropertyName ramp_scheduled_at -NotePropertyValue $slot.scheduled_at -Force
  $row | Add-Member -NotePropertyName ramp_queue_status -NotePropertyValue $slot.queue_status -Force
  $row | Add-Member -NotePropertyName ramp_label -NotePropertyValue $slot.ramp_label -Force
  [void]$rampRows.Add($row)
}

New-Item -ItemType Directory -Path (Split-Path -Parent $OutputCsv) -Force | Out-Null
$rampRows | Export-Csv -LiteralPath $OutputCsv -NoTypeInformation -Encoding UTF8

$lines = New-Object "System.Collections.Generic.List[string]"
$lines.Add("-- Generated by scripts/build-outbound-ramp-seed.ps1") | Out-Null
$lines.Add("-- Campaign: $CampaignId") | Out-Null
$lines.Add("-- Start local date: $StartDate America/Buenos_Aires") | Out-Null
$lines.Add("-- Day 1 rows are pending. Later days are held until manually released.") | Out-Null
$lines.Add("") | Out-Null
$lines.Add("DELETE FROM outbound_send_queue WHERE campaign_id = '$CampaignId' AND status IN ('pending', 'held', 'cancelled');") | Out-Null
$lines.Add("DELETE FROM outbound_prospects WHERE sequence_id = '$CampaignId' AND status IN ('scheduled', 'approved', 'pending', 'paused');") | Out-Null
$lines.Add("") | Out-Null

foreach ($row in $rampRows) {
  $queueId = "$CampaignId`:$($row.id):1"
  $prospectStatus = if ($row.ramp_queue_status -eq "pending") { "scheduled" } else { "approved" }
  $lines.Add(@"
INSERT OR REPLACE INTO outbound_prospects (
  id, company_name, website, domain, email, email_type, contact_route,
  contact_name, contact_role, industry, sub_industry, company_type,
  country, province, city, icp_fit, icp_score, priority, source,
  campaign_segment, sequence_id, sequence_step, status, tags,
  validation_flags, last_sent_at, next_send_at, replied_at, bounced_at,
  unsubscribed_at, do_not_contact_reason, notes, created_at, updated_at
) VALUES (
  $(Sql-String $row.id),
  $(Sql-String $row.company_name),
  $(Sql-String $row.website),
  $(Sql-String $row.domain),
  $(Sql-String $row.email),
  $(Sql-String $row.email_type),
  $(Sql-String $row.contact_route),
  $(Sql-String $row.contact_name),
  $(Sql-String $row.contact_role),
  $(Sql-String $row.industry),
  $(Sql-String $row.sub_industry),
  $(Sql-String $row.company_type),
  $(Sql-String $row.country),
  $(Sql-String $row.province),
  $(Sql-String $row.city),
  $(Sql-String $row.icp_fit),
  $([int]$row.icp_score),
  $(Sql-String $row.priority),
  $(Sql-String $row.source),
  $(Sql-String $row.campaign_segment),
  $(Sql-String $CampaignId),
  0,
  $(Sql-String $prospectStatus),
  $(Sql-String $row.tags),
  $(Sql-String $row.validation_flags),
  NULL,
  $(Sql-String $row.ramp_scheduled_at),
  NULL,
  NULL,
  NULL,
  NULL,
  $(Sql-String ($row.notes + " | ramp_label: " + $row.ramp_label)),
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
);

INSERT OR REPLACE INTO outbound_send_queue (
  id, campaign_id, prospect_id, step_number, scheduled_at, status,
  attempts, created_at, updated_at
) VALUES (
  $(Sql-String $queueId),
  $(Sql-String $CampaignId),
  $(Sql-String $row.id),
  1,
  $(Sql-String $row.ramp_scheduled_at),
  $(Sql-String $row.ramp_queue_status),
  0,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
);
"@) | Out-Null
}

New-Item -ItemType Directory -Path (Split-Path -Parent $OutputSql) -Force | Out-Null
$lines -join "`n" | Set-Content -LiteralPath $OutputSql -Encoding UTF8

$summary = $rampRows | Group-Object ramp_label, ramp_queue_status, ramp_local_date | Sort-Object Name | Select-Object Count, Name

[PSCustomObject]@{
  output_csv = $OutputCsv
  output_sql = $OutputSql
  eligible_unique = $eligible.Count
  scheduled_rows = $rampRows.Count
  pending_today = @($rampRows | Where-Object ramp_queue_status -eq "pending").Count
  held_future = @($rampRows | Where-Object ramp_queue_status -eq "held").Count
  summary = $summary
}
